domain = geolocation
source_path = /Volumes/main/dev_storage/commercelake_raw/geolocation
target_table = main.dev_bronze.bronze_geolocation
file_format = csv
header = true
delimiter = ,
schema_evolution = addNewColumns
schema_location = /Volumes/main/dev_storage/commercelake_metadata/schema/geolocation
output_mode = append
checkpoint_location = /Volumes/main/dev_storage/commercelake_metadata/checkpoint/geolocation