domain = orders
source_path = /Volumes/main/dev_storage/commercelake_raw/orders
target_table = main.dev_bronze.bronze_orders
file_format = csv
header = true
delimiter = ,
schema_evolution = addNewColumns
schema_location = /Volumes/main/dev_storage/commercelake_metadata/schema/orders
output_mode = append
checkpoint_location = /Volumes/main/dev_storage/commercelake_metadata/checkpoint/orders