domain = orderlist
source_path = /Volumes/main/dev_storage/commercelake_raw/orderlist
target_table = main.dev_bronze.bronze_orderlist
file_format = csv
header = true
delimiter = ,
schema_evolution = addNewColumns
schema_location = /Volumes/main/dev_storage/commercelake_metadata/schema/orderlist
output_mode = append
checkpoint_location = /Volumes/main/dev_storage/commercelake_metadata/checkpoint/orderlist