domain = products
source_path = /Volumes/main/dev_storage/commercelake_raw/products
target_table = main.dev_bronze.bronze_products
file_format = csv
header = true
delimiter = ,
schema_evolution = addNewColumns
schema_location = /Volumes/main/dev_storage/commercelake_metadata/schema/products
output_mode = append
checkpoint_location = /Volumes/main/dev_storage/commercelake_metadata/checkpoint/products